---
apiVersion: v1
kind: Pod
metadata:
  namespace: run-job
  name: JOB_NAME_PLACEHOLDER
spec:
  schedulerName: my-scheduler
  containers:
  - name: job
    image: polinux/stress
    resources:
      requests:
        memory: MEMORY_PLACEHOLDER
        cpu: CPU_PLACEHOLDER
        ephemeral-storage: EPHEMERAL_STORAGE_PLACEHOLDER
    command: ["/bin/sh", "-c"]
    args: ["timeout TIMEOUT_PLACEHOLDER stress --vm 1 --vm-bytes MEMORY_STRESS_PLACEHOLDER --vm-hang 1"]
  restartPolicy: Never
